version: '3'

services:
  db:
    container_name: harald_fairhair
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=harald_fairhair
      - POSTGRES_PASSWORD=harald_fairhair
      - POSTGRES_DB=harald_fairhair
