# ===============================
# [ Server Properties ]
# ===============================
server:
  port: 9090

# ===============================
# [ Spring Properties ]
# ===============================
spring:
  datasource:
    url: jdbc:h2:mem:post;MODE=PostgreSQL;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    driverClassName: "org.h2.Driver"
    initialize: true
    data: classpath:*data.sql
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    database: h2
    show-sql: true
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: true

# ===============================
# [ JWT Properties ]
# ===============================
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        solairerove:
          harald: DEBUG
    org:
      springframework: INFO
      hibernate: ERROR
