# ===============================
# [ Face palm Properties ]
# ===============================
face_palm:
  app:
    name: Face Palm
  db:
    url: postgresql://localhost:5433/face_palm_local
    username: face_palm_local
    password: face_palm_local

# ===============================
# [ Server Properties ]
# ===============================
server:
  port: 9090
  undertow:
    accesslog:
      enabled: true
      dir: target/logs
      pattern: combined
  compression:
    enabled: true
    min-response-size: 1

# ===============================
# [ Spring Properties ]
# ===============================
spring:
  application:
    name: ${face_palm.app.name}
  datasource:
    url: jdbc:${face_palm.db.url}
    username: ${face_palm.db.username}
    password: ${face_palm.db.password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: true


# ===============================
# [ Flyway Properties ]
# ===============================
flyway:
  enabled: true
  locations: classpath:db/migration

# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        solairerove:
          facepalm:
            spring:
              groovy: DEBUG
    org:
      springframework: INFO
      hibernate: ERROR
      flywaydb: INFO
