# ===============================
# [ Face palm Properties ]
# ===============================
face_palm:
  app:
    name: Face Palm
  db:
    url: postgresql://localhost:5432/face_palm_local
    username: face_palm_local
    password: face_palm_local

# ===============================
# [ Server Properties ]
# ===============================
server:
  port: 9090

# ===============================
# [ Spring Properties ]
# ===============================
spring:
  application:
    name: ${face_palm.app.name}
  datasource:
    url: jdbc:${face_palm.db.url}
    username: ${face_palm.db.username}
    password: ${face_palm.db.password}
    initialize: true
    init-sql: classpath:*schema.sql
    data: classpath:*data.sql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: true

# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        solairerove:
          facepalm: DEBUG
    org:
      springframework: INFO
      hibernate: ERROR
      flywaydb: INFO
