# ===============================
# [ Server Properties ]
# ===============================
server:
  port: 9090

# ===============================
# [ Spring Data JPA Properties ]
# ===============================
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    generate-ddl: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: harald_fairhair
    password: harald_fairhair
    name: harald_fairhair
    initialize: true

# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        solairerove:
          harald: DEBUG
    org:
      springframework: INFO
      hibernate: ERROR
